name: CI

on:
  push:
    branches:
      - vanilla
      - vanilla-dev
      - expansion
      - expansion-dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      AUTOMATION_HOST: GITHUB
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout agbcc
        uses: actions/checkout@v3
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install Dependencies
        run: |
          ./init_deps.sh

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Agbcc
        run: make -j${nproc} -O all
      - uses: actions/upload-artifact@v2
        with:
          name: pokerogue
          path: pokeemerald.gba
          
      - uses: actions/upload-artifact@v2
        with:
          name: pokerogue_elf
          path: pokeemerald.elf
          
      - uses: actions/upload-artifact@v2
        with:
          name: pokerogue_map
          path: pokeemerald.map

      - name: Update Memory Stats
        uses: actions/upload-artifact@v3
        with:
          name: Memory Stats
          path: pokeemerald_memorystats.csv

      # - name: Modern
      #   env:
      #     MODERN: 1
      #     COMPARE: 0
      #   run: make -j${nproc} -O all

      # - name: Test
      #   run: |
      #     make -j${nproc} -O pokeemerald-test.elf
      #     make -j${nproc} check
